services:
  back: 
    build: ./back  
    container_name: back_docker_test 
    restart: always
    env_file:
      - ./back/.env
    ports:
      - "3333:3333"
    depends_on:
      - db

  db:
    image: postgres:15 #Nesse caso busquei uma imagem no hub
    environment: # Variaveis que meu container terão, dica: sempre buscar de algum serviço de secret, puipeline, mas nunca no modo hard code
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
	    - postgres_data:/var/lib/postgresql/data #Informar onde esse serviço irá salvar os dados
    ports:
      - "5432:5432"
  volumes:
  postgres_data: