services:
  back: 
    build: ./back  
    container_name: back_docker
    restart: always
    env_file:
      - ./back/.env
    ports:
      - "3333:3333"
    depends_on:
      - db

  db:
    image: postgres:14.18
    container_name: bd_pg_docker 
    env_file:
      - ./back/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres_data: